nodeLinker: node-modules

plugins:
  - checksum: 06693e9fc7fab4f284ea0579b839c1503a83b4acd57dd49043e5f4528b9961b01b60049cfec3872a96f4957f36788b5b99e211d78e2bfd920f7f494f11bc16b6
    path: .yarn/plugins/@mdreal/plugin-env.cjs
    spec: "https://github.com/MDReal32/yarn-plugin-env/releases/download/latest/plugin-env.js"

yarnPath: .yarn/releases/yarn-4.0.2.cjs

npmRegistryServer: "https://npm.pkg.github.com"
npmAuthToken: $NODE_AUTH_TOKEN
