name: Publish to NPM

on:
  push:
    branches:
      - master

jobs:
  publish:
    name: Publish @kubejs/${{ matrix.package_name }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        package_name:
          - core
          - plugin
          - generator
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v3
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        with:
          node-version: 24
          registry-url: 'https://registry.npmjs.org'

      - name: Enable yarn
        run: corepack enable

      - name: Install dependencies
        run: yarn

      - name: Build @kubejs/${{ matrix.package_name }} app
        run: yarn nx run @kubejs/${{ matrix.package_name }}:vite:build

      - name: Publish @kubejs/${{ matrix.package_name }}
        run: |
          sed -i 's/\$NODE_AUTH_TOKEN/${NODE_AUTH_TOKEN}/g' .yarnrc.yml
          yarn workspace @kubejs/${{ matrix.package_name }} publish-me
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        continue-on-error: true
