name: Publish to NPM

on:
  push:
    branches:
      - master

jobs:
  publish:
    name: Publish ${{ matrix.package_name }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        package_name: ["plugin", "generator"]
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v3
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        with:
          node-version: 20
          registry-url: 'https://registry.npmjs.org'



      - name: Cache folder
        id: cache-folder
        uses: actions/cache@v4
        with:
          path: kube-js/${{ matrix.package_name }}
          key: ${{ runner.os }}-dir-${{ hashFiles(format('kube-js/{0}', matrix.package_name)) }}
          restore-keys: |
            ${{ runner.os }}-dir-${{ matrix.package_name }}

      - name: Check if folder has changed
        id: folder-changed
        run: |
          echo "changed=false" >> $GITHUB_OUTPUT
          if [ -d "kube-js/${{ matrix.package_name }}" ]; then
            git fetch origin master
            changes=$(git diff --name-only HEAD origin/master -- "kube-js/${{ matrix.package_name }}" | wc -l)
            if [ "$changes" -gt 0 ]; then
              echo "changed=true" >> $GITHUB_OUTPUT
            fi
          fi

      - run: corepack enable
        if: steps.folder-changed.outputs.changed == 'true'

      - run: yarn
        if: steps.folder-changed.outputs.changed == 'true'

      - run: yarn workspace ${{ matrix.package_name }} build
        if: steps.folder-changed.outputs.changed == 'true'

      - run: yarn workspace ${{ matrix.package_name }} publish:me
        if: steps.folder-changed.outputs.changed == 'true'
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
